config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
post 'create_comments', :to => 'wiki_comments#create'
get 'test_method', :to => 'wiki_comments#test_method'

app/models/wiki_page_comment.rb
require 'diff'
require 'enumerator'

class WikiPageComment < WikiPage
  has_many :comments, lambda {order("created_on")}, :as => :commented, :dependent => :delete_all
end

app/models/wiki_plugin.rb
require 'diff'
require 'enumerator'

class WikiPlugin
  has_many :pages, lambda {order('title')}, :class_name => 'WikiPageComment', :dependent => :destroy
end

app/controllers/wiki_comments_controller.rb
class WikiCommentsController < ApplicationController
  unloadable

  def create
  	@project = Project.find(params[:project_id])
  	@wiki = @project.wiki 
    @wiki_pages_comments = WikiPageComment.where(wiki_id:@wiki.id)
  	@wiki_page = @wiki_pages_comments.find_by_title(params[:page_id])
  	puts "----#{@wiki_page.id}"
  	@user = User.find(params[:user_id])
    if @user.present? 
  		@comment = @wiki_page.comments.new(commented_type: "WikiPage", commented_id: @wiki_page.id, author_id: @user.id, content: params[:wiki_page][:comment])
  		if @comment.save
        @wiki_pages_comments = @wiki_page.comments
        flash[:notice] = l(:notice_successful_create)
  			redirect_to :back
  		else
        @wiki_pages_comments = @wiki_page.comments
  			redirect_to project_wiki_page_path(@project,@wiki_page.id)
  		end	
  	else
      @wiki_pages_comments = @wiki_page.comments
  		redirect_to project_wiki_page_path(@project,@wiki_page.id)
  	end	
  end

end

app/helpers/wiki_comments_helper.rb
module WikiCommentsHelper

	def self.show_comments(wiki,id)
		wiki_page = wiki.pages.find_by(title: id)
		WikiPageComment.find_by(title: wiki_page.title).try(:comments)
	end
end

app/views/comment_section/_comment_section_view.html.erb
<% if params[:id].present? %>
	<form action="<%= create_comments_path %>" method = "post">
		<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
		
		<input name="page_id" value="<%= params[:id]%>" type="hidden">
		<input name="project_id" value="<%= params[:project_id]%>" type="hidden">
		<input name="user_id" value="<%= User.current.id%>" type="hidden">

		<h2>Comments section</h2>
		<div class="row">
			<div class="col-md-10">
				<textarea placeholder="comment" name="wiki_page[comment]" style="width: 100%;height: 60px;"></textarea>
			</div>
			<div class="col-md-2">
				<button type="submit">Add Comment</button>
			</div>
		</div>
	</form>
	<%if @wiki_pages_comments.blank?%>
		<% @wiki_pages_comments = WikiCommentsHelper.show_comments(@wiki,params[:id])%>
	<%end%>
	<%if @wiki_pages_comments.present?%>
		<div id="comments" style="margin-bottom:16px;margin-top:16px;">
			<h3 class="comments">Comments</h3>
			    <% @wiki_pages_comments.order('id ASC').each do |comment| %>
			    <h4>Added by <a class="user active" href="/users/<%=comment.author.id%>"><%= comment.author.firstname%>, <%= comment.created_on.strftime("%-d/%-m/%y: %H:%M %Z")%></a></h4>
			    <div class="wiki">
			    	<p><%= comment.content%></p>
			    </div>
			    <% end %>
			</div>
	<%end%>
<%end%>